import { User } from "../interfaces/users";

//  Dummy users
export const users: User[] = [
  {
    id: '1',
    login: 'John',
    password: 'qwerty1ER',
    age: 26,
    isDeleted: false,
  },
  {
    id: '2',
    login: 'Paul',
    password: 'qwerty1ER4',
    age: 27,
    isDeleted: false,
  },
  {
    id: '3',
    login: 'Ringo',
    password: 'qwerty1ER2',
    age: 27,
    isDeleted: false,
  },
  {
    id: '4',
    login: 'George',
    password: 'qwerty3GGG',
    age: 27,
    isDeleted: false,
  },
  {
    id: '5',
    login: 'Kurt',
    password: 'inBloom1',
    age: 27,
    isDeleted: false,
  },
  {
    id: '6',
    login: 'Krist',
    password: 'inBloom2',
    age: 27,
    isDeleted: false,
  },
  {
    id: '7',
    login: 'Dave',
    password: 'inBloom3',
    age: 27,
    isDeleted: false,
  },
  {
    id: '8',
    login: 'Jack',
    password: 'NationArmy7',
    age: 30,
    isDeleted: false,
  },
  {
    id: '9',
    login: 'Mag',
    password: 'NationArmy77',
    age: 31,
    isDeleted: false,
  },
  {
    id: '10',
    login: 'Antony',
    password: 'cantStop2000',
    age: 40,
    isDeleted: false,
  },
  {
    id: '11',
    login: 'JohnF',
    password: 'cantStop20001',
    age: 39,
    isDeleted: false,
  },
  {
    id: '12',
    login: 'Flea',
    password: 'cantStop20002',
    age: 41,
    isDeleted: false,
  },
  {
    id: '13',
    login: 'Chad',
    password: 'cantStop20003',
    age: 50,
    isDeleted: false,
  },
  {
    id: '14',
    login: 'James',
    password: 'frantic1',
    age: 58,
    isDeleted: false,
  },
  {
    id: '15',
    login: 'Lars',
    password: 'frantic2',
    age: 58,
    isDeleted: false,
  },
  {
    id: '16',
    login: 'Kirk',
    password: 'frantic3',
    age: 58,
    isDeleted: false,
  },
  {
    id: '17',
    login: 'Robert',
    password: 'frantic4',
    age: 58,
    isDeleted: false,
  },

];